### ISSUE TITLE
Non supported languages

### ISSUE THREAD

**Issue by DinoStarcic** [Abedalkareem/LanguageManager-iOS#15] opened 2019-04-14 13:34 UTC
Hi im trying to use this with Slovenian language which is it the section of "other" your enum does not have the .sl lang. How can i bypass this to make it work? :)

**Comment by Abedalkareem** [comment] 2019-04-14 14:13
Hi,

Thank you for reporting! 
This issue fixed on 1.1.0 version, please update the pods and if the issue is still there please reply here.

Thank you.

**Closed by Abedalkareem** 2019-04-14 14:13 UTC

**Comment by DinoStarcic** [comment] 2019-04-14 16:40
Hi :) Now it compiled the project but it dosent read from the .sl strings file, it works normally with .en

**Comment by DinoStarcic** [comment] 2019-04-14 17:02
:) this seems to change it when i re run the app :D  

LanguageManager.shared.defaultLanguage = .de

LanguageManager.shared.setLanguage(language: .sl)
